Ben/dev 80
plastic-labs/tutor-gpt pull request #153
Opened 2024-10-16 16:28 UTC by bLopata

2024-10-25 15:56 UTC, VVoruganti commented on www/components/sidebar.tsx
> +        className={`h-full scrollbar-trigger overflow-hidden bg-white dark:bg-gray-950 dark:text-white sm:w-3/5 w-4/5 lg:w-full flex flex-col ${
<img width="894" alt="image" src="https://github.com/user-attachments/assets/e908251f-f457-4e66-9732-31e299043210">

Text in sidebar is white in dark mode, makes it hard to read, should stay black the entire time

2024-10-25 15:59 UTC, VVoruganti commented on www/app/page.tsx
>        <Sidebar
Can't open the left sidebar in mobile
<img width="377" alt="image" src="https://github.com/user-attachments/assets/522131a2-199f-463c-aa7d-2a423d747455">

2024-10-25 16:03 UTC, VVoruganti commented
<img width="288" alt="image" src="https://github.com/user-attachments/assets/ddeac567-1685-4570-bcfa-eccd90e097fe">
Should have some kind of visual distinction between top bar and the start of the sidebar

2024-10-25 16:08 UTC, VVoruganti requested changes
Going to try to consolidate my feedback in this comment, 

This is the settings sidebar and there should some visual indication of which page is selected, along with a visual indication of a hover i. e. `transform background color`

<img width="270" alt="image" src="https://github.com/user-attachments/assets/085150c7-e10e-4f9f-8794-964086cd9424">

Horizontal Bar should be above the Email Label to associate it with that one

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/47e01fee-038f-4396-bfd7-a21993b73cc4">

It is failing to `pnpm run build`

<img width="734" alt="image" src="https://github.com/user-attachments/assets/09335a9b-6d3d-47bd-88fe-d5d9705f7d12">


- [ ] Also make sure you run lint and pretty

2024-10-25 18:23 UTC, VVoruganti commented on www/package.json
> +    "lucide-react": "^0.452.0",
We shouldn't be using `lucide-react` and `react-icons` basically let's try to only use one icon library

2024-10-25 19:43 UTC, bLopata commented
@VVoruganti addressed all your comments
https://app.screencast.com/EEwkjY4NPydpM

2024-10-28 14:54 UTC, VVoruganti commented
Do you have a list of edge cases that were tested with the `linkIdentity` feature and the behavior?

2024-10-28 15:34 UTC, VVoruganti requested changes
![image](https://github.com/user-attachments/assets/9f416f68-69a7-4bf8-902a-c2b035a9a022)

Buttons on Auth Pages don't have proper dark mode handling

Seeing weird behavior when testing manual linking. Steps to reproduce

1. Have one account that is authenticated with an email
2. Have another account that is authenticated via discord with a different email 

From the first account try to connect your discord identity. When you connect via the oauth flow, the screen will return to the settings page with an `?error` in the url address, however the user will not be authenticated anymore and no errors will print or register in the logic handler. 

Since the user's authentication session is invalidated they should be redirected to the /auth screen. May need to manually add a `redirect` call in the `SettingsPage`

I'm seeing the error in the url, but I don't know why it is invalidating the auth session. 

---
Another edge case is if I have a user with an account that is connected via Discord then I unlink my discord account I then have no password associated with the account. 

Going through the password recovery flow returns an error.

2024-11-04 23:19 UTC, VVoruganti approved these changes

2024-11-04 23:22 UTC, merged