Ben/dev 464 - Free allotment for New Users
plastic-labs/tutor-gpt pull request #169
Opened 2024-11-11 22:35 UTC by bLopata

Adds header for unsubscribed users showing the current message count.

![image](https://github.com/user-attachments/assets/39e749d4-b7f4-4f15-867e-e51afaf37cb9)

https://app.screencast.com/TbIeO77iS61MH

2024-11-15 17:07 UTC, VVoruganti requested changes
You also need to change the api/ folder to check for valid subscription or a remaining trial.

Should be in the `/api/security` file

2024-11-15 18:23 UTC, bLopata commented
> You also need to change the api/ folder to check for valid subscription or a remaining trial.
> 
> Should be in the `/api/security` file

Good call. Thinking something like this:
` sub = (
        supabase.table("subscriptions")
        .select("*")
        .eq("user_id", user.id)
        .or_(
            "status.eq.active,"  # Active subscriptions
            "and(status.eq.trialing,trial_end.gte.now())"  # Valid trial subscriptions
        )
        .execute()
    )`

unless you think we should have this call check the freeMessage allotment as well? Didn't know if that would be too tightly coupled.

2024-11-18 19:43 UTC, VVoruganti requested changes

2024-11-18 19:43 UTC, VVoruganti commented on www/utils/supabase/admin.ts
> +    current_period_end: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().replace('T', ' ').replace('Z', ''), // 1 year
Need to think through if it makes sense to send an end date for a year or just have no end date

2024-11-18 19:43 UTC, VVoruganti commented on www/utils/supabase/admin.ts
> +    status: 'trialing',
By manually inserting a subscription to the database we have a weird situation where there is no data in stripe linking the customer and Bloom user. Also our subscription check will get one subscription and if a user pays for a subscription, but also has a trialing subscription it'll lead to weird behavior.

2024-11-18 19:43 UTC, VVoruganti commented on www/utils/supabase/admin.ts
> +    .eq('id', subscription.id);
Can combine this into a single database operation example from claude:

```typescript
const { error: updateError } = await supabaseAdmin
  .from('subscriptions')
  .update({
    'metadata->freeMessages': 'metadata->freeMessages - 1'
  })
  .eq('id', subscription.id)
  .gt('metadata->freeMessages', 0); // Only update if freeMessages > 0

// Check if any rows were affected
if (updateError) return false;
```

2024-11-19 19:26 UTC, merged